### ISSUE TITLE
modify do it works with phenix 1.15

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-phenix#2]

**Comment by rmarabini** [comment]
OK, there is no pickle option in phenix 1.14 but it is back in phenix 15 so we fix the protocol dor scipion 1.15. By the way molprobity is gone now the equivalent phenix protocol is scipin_validate_cryoem

**Comment by mmmtnez** [comment]
works with phenis 1.13 and 1.16 which are the offitial releases
