### ISSUE TITLE
Error installing as a dependency

### ISSUE THREAD

**Issue by martin-s-a** [scipion-em/scipion-em-phenix#78]
In [scipion-em-kiharalab](https://github.com/scipion-em/scipion-em-kiharalab), I have recently encountered an issue while installing related to installing this plugin as a dependency. The specific error can ve viewed in [this sample build action](https://github.com/scipion-em/scipion-em-kiharalab/actions/runs/5271849186/jobs/9533305036).
It seems to be related to the package `tk_html_widgets`, which contains an invalid specifier in this line of `setup.py`:
```Python
python_requires=">=3.4.*",
```
This specifier is invalid since [PEP 440](https://peps.python.org/pep-0440/#version-specifiers). I couldn't find which Python version was the first to implement it, but a clean docker image (where GitHub actions are launched) with Ubuntu 22.04 cannot install Python 3.4 via [predefined actions](https://github.com/actions/setup-python), and it would not make sense to install such version since scipion uses Python Python 3.8.16 anyway.

This was my `requirements.txt` file prior to the test:
```
scipion-pyworkflow
scipion-em
scipion-em-phenix
mrcfile
```
And this is the error it produced:
```
Collecting scipion-em-chimera>=3.0.1 (from scipion-em-ccp4>=3.0.0->scipion-em-phenix->scipion-em-kiharalab==1.0)
  Downloading scipion_em_chimera-3.3.5-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.6/163.6 kB 11.1 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /home/runner/work/scipion-em-kiharalab/miniconda/envs/scipion3/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib==3.5.2->scipion-pyworkflow->scipion-em-kiharalab==1.0) (1.16.0)
Collecting tk-html-widgets (from scipion-em-chimera>=3.0.1->scipion-em-ccp4>=3.0.0->scipion-em-phenix->scipion-em-kiharalab==1.0)
  Downloading tk_html_widgets-0.4.0.tar.gz (9.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in tk_html_widgets setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.4.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
After removing `scipion-em-phenix` from the `requirements.txt` file, the error disappears and the build completes successfully, that's why I'm certain this issue is deep down a dependency issue with this plugin.

**Comment by azazellochg** [comment]
Hi @MartinSalinas98 ,this has been fixed in the chimera plugin

**Comment by martin-s-a** [comment]
Hi @azazellochg, it's true, it does work now. Closing iisue.
